### ISSUE TITLE
Syntax highliting (SCSS?) @sounmind

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#102]

**Comment by sounmind** [comment]
Name: CSS Nesting Syntax Highlighting
Id: jacobcassidy.css-nesting-syntax-highlighting
Description: Updates VSCode's CSS TextMate rules to add CSS Nesting
Version: 0.1.0
Publisher: Jacob Cassidy
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=jacobcassidy.css-nesting-syntax-highlighting

이거 설치하면 해결되네요! 오예~!!



![Image](https://github.com/DaleStudy/leetcode-website/assets/37020415/9ed51b09-46d6-464d-913d-9b3b6014a1fa)

**Comment by yolophg** [comment]
> Name: CSS Nesting Syntax Highlighting Id: jacobcassidy.css-nesting-syntax-highlighting Description: Updates VSCode's CSS TextMate rules to add CSS Nesting Version: 0.1.0 Publisher: Jacob Cassidy VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=jacobcassidy.css-nesting-syntax-highlighting
> 
> 이거 설치하면 해결되네요! 오예~!!
> 
> ![Image](https://private-user-images.githubusercontent.com/37020415/345682627-9ed51b09-46d6-464d-913d-9b3b6014a1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjIyNzQsIm5iZiI6MTcyMDA2MTk3NCwicGF0aCI6Ii8zNzAyMDQxNS8zNDU2ODI2MjctOWVkNTFiMDktNDZkNi00NjRkLTkxM2QtOWIzYjYwMTRhMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyNTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0Y2RkMDBlZGM5ZmMxNTgzZmE0YzcxM2EzYTcyNDFlOGM4NjBmODg2OTAzMjA2ZGVhNDVlY2MxZTRlMGYwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u0TSTfRa647LVh6uW0TeJDK2R-UZQ7TE-98ENgHlbgM)

오! 감사합니다!!!

**Comment by DaleSeo** [comment]
@sounmind 그 전에 썼던 익스텐션이 뭐였죠? 그 걸 지우고 설치하고 싶은데 ㅋㅋ

**Comment by DaleSeo** [comment]
#42 에서 찾았습니다. 신경쓰지 마세염 :)
