### ISSUE TITLE
Specify design specs for buttons and links by state

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leetcode-website#106]
관련 이슈: #96 

마우스로 클릭하거나 키보드 탭으로 이동할 때 현재 어떤 요소에 포커스가 있는지 육안으로 파악이 가능하려면, 버튼이나 링크의 상태에 대한 스타일을 해줘야 합니다. 이를 위해서 `focus`나 `fcous-visible`에 대한 스타일은 반드시 필요하고, `hover`, `active`, `visited`, `active` 상태에 대한 스타일은 선택이지만 해주면 사용성이 더 좋아집니다.

제가 말씀드렸던 웹 접근성 달성하기 위해서 개발자들이 임의로 적당히 효과를 넣어줄 수도 있지만, Figma에 버튼과 링크의 디자인 스팩이 상태에 따라서 더 구체화가 되면 더 좋을 것 같습니다.

**Comment by DaleSeo** [comment]
@nhistory 님, 위 요구사항이 통상적인 Product Design의 범위가 넘어가는데 가능하실려나 모르겠습니다. 이러한 디자인 작업을 안 해보셨다면 나름 신선한 도전이 되실 수 있지 않을까요? 😅

**Comment by nhistory** [comment]
네 어떻게 구현하면 좋을지 고민을 해봐야겠네요 ㅎㅎ

**Comment by nhistory** [comment]
@DaleSeo 아래 이미지와 같이 상태에 대한 스타일링을 구성해 보았습니다.
공유해주셨던 [글](https://www.daleseo.com/css-html-a/)에서 visited는 프라이버시 이슈 때문에 사용하지 않는 추세라고 하셔서 스타일링에서는 제외하였습니다.

![Image](https://github.com/DaleStudy/leetcode-website/assets/39740066/18890bfe-c033-4ef1-9235-f3385f44beb5)


@sounmind 현재 button-link 컴포넌트에 적용하기에 적절한지 피드백 부탁드립니다. footer에 있는 링크들도 '참여방법 안내' 링크와 동일한 스타일링으로 적용하면 좋을 것 같습니다.

**Comment by sounmind** [comment]
@nhistory 이 스타일링에 이견은 없습니다. button-link나 여타 컴포넌트에도 적용하는데 어려움은 없어보입니다.

**Comment by sounmind** [comment]
@nhistory 그리고 유형 별로 다 스타일이 달라서 그런데, 아이콘이나 텍스트 링크의 경우에는 어떻게 처리하면 좋을까요?

**Comment by nhistory** [comment]
@sounmind footer 안에 있는 링크들 말씀하시는거죠? 그 부분도 정리해서 공유하겠습니다.

**Comment by sounmind** [comment]
@nhistory footer 안의 링크랑 헤더의 로고, 메뉴/닫기 버튼도요!

**Comment by nhistory** [comment]
@sounmind 자세한 스펙은 피그마 프로젝트에서 확인 가능합니다.
![image](https://github.com/DaleStudy/leetcode-website/assets/39740066/16dd0197-8aab-4af5-a8d0-5a0c96cb556e)

모든 상태에 대한 스타일링이 바뀔 때 200ms transition이 들어가면 좋을 것 같습니다. :^)
