### ISSUE TITLE
Discuss the ever-expanding PR problem

### ISSUE THREAD

**Issue by yolophg** [DaleStudy/leetcode-website#113]
## Background
- PR이 계속해서 그 기능보다 더 확장되고 있는 문제
_ex) 처음엔 create component의 목적만 가진 PR이 responsive, color, 그것을 감싸는 list, section 등 여러 기능까지 같이 확장되어서 create component라는 하나의 PR에 포함이 됨._

## Cause and Solution
- PR이 꽤 긴 기간동안 오픈되어있다 -> **리뷰어들은 가능한 빠르게 review를 해주고, pr 작성자는 가능한 빠르게 review를 반영하자**
- 확장된다해도, 여러 feature를 한 pr에 포함시키고있다 -> **pr 작성자는 ticket에 따라 가능한 작은 단위로 pr을 분리하자**

**Comment by SamTheKorean** [comment]
저도 작업하면서 생각했던 부분이었는데 꺼내주셔서 감사합니다! 뿐만 아니라 pr 작업중 컨벤션 수정등으로 인해 계속해서 수정할 상황이 생겨서 늦게 닫힌 부분도 있는 것 같습니다.

**Comment by DaleSeo** [comment]
PR은 가급적 작게, 하나의 티켓에 여러 개의 PR을 생성해도 무방. 반대는 피할 것
