### ISSUE TITLE
Discuss attribute convention

### ISSUE THREAD

**Issue by yolophg** [DaleStudy/leetcode-website#114]
## 현재 사용되고 있는 attribute 컨벤션 종류 정리
1. camelCase 
   e.g) iconSrc
2. kebab-case 
   e.g) icon-src

**Comment by yolophg** [comment]
camel case는 먹히지 않음. 모두 lowercase로 변환됨 @sounmind

**Comment by DaleSeo** [comment]
변수 이름은 camelCase, 속성 이름은 kabab-case로 통일하기로 결정
