### ISSUE TITLE
[BUG] Logo 파일 이름 대소문자 이슈로 보이지 않는 문제

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#115]
현상: Logo 파일이 보이지 않고 있음. 파일을 찾을 수 없는 문제.

![Image](https://github.com/DaleStudy/leetcode-website/assets/37020415/7ed56002-d6d1-4011-85b2-7df813684c88)

원인:
- 코드에서는 logo.png를 찾고 있지만, 소스코드에는 Logo.png라는 이름으로 저장되어 있음.
- 해당 작업자 git의 ignore case 옵션이 켜져 있기 때문에 발생했던 문제로 추정.

해결:
- logo.png로 파일 이름을 변경한다.
- 앞으로 같은 문제가 발생하지 않기 위해서는 ignore case 옵션을 false로 하거나, 파일 이름의 대소문자를 확실히 구분하면서 작업해야 함.

**Comment by SamTheKorean** [comment]
이 부분 고쳤다가 커밋에서 누락했네요 지금 바로 pr 만들겠습니다!

**Comment by sounmind** [comment]
@SamTheKorean 지금 open되어 있는 PR 승인해주시면 되어요~
