### ISSUE TITLE
Branch naming rule

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#12]
### Background
- to avoid branch name duplication

### Convention
- prefix branch name with branch owner's name
- for example:
  - `evan/123` (issue number)
  - `evan/add-card-component` (A name that represents the change)

**Comment by SamTheKorean** [comment]
So we get to choose either one based on our preference?

**Comment by sounmind** [comment]
> So we get to choose either one based on our preference?

Yes, what do you think?

**Comment by SamTheKorean** [comment]
Sounds good to me:)
