### ISSUE TITLE
Share issue with Media Queries in Shadow DOM

### ISSUE THREAD

**Issue by yolophg** [DaleStudy/leetcode-website#124]
## Problem
::slotted() 선택자가 단순히 slotted된 요소의 일차적인 스타일링만을 허용하고, 중첩 스타일링과 미디어 쿼리는 지원하지 않음.
* 지난번 shadowDOM children에 스타일링 불가한 이슈와 유사 => https://github.com/DaleStudy/leetcode-website/issues/80

## Example
step-list 내에 있는 ds-step 아이템에 스크린 크기에 따른 별도 스타일을 적용하고 싶은 상황
```js
.step-list ::slotted(ds-step) {
/* working */
  flex: 1 1 100%;

  @media only screen and (min-width: 768px) {
    /* not working */
  }
}
```

## Result
- step-list에서 필수적으로 접근해야하는 경우는 아니었기 때문에, 아이템 자체에 스타일링을 적용해서 해결
- 하지만, 추후 컴포넌트 개발이 있을 시, 상위 컴포넌트에서 -> 슬롯 하위 컴포넌트를 스타일링 컨트롤 해야하는 경우에는 꼭 이 점을 고려해서 설계 및 스타일링 할 필요가 있음

**Comment by DaleSeo** [comment]
공유 완료
