### ISSUE TITLE
Create Text Link Component in Footer

### ISSUE THREAD

**Issue by bhyun-kim** [DaleStudy/leetcode-website#14]

**Comment by bhyun-kim** [comment]
@sounmind Discord에도 올려드렸는데, 여기서 이야기 나누는게 표준인 것 같아 여기도 올려요. 

이런 방식으로 진행하면 괜찮을까요? 

![image](https://github.com/DaleStudy/leetcode-website/assets/94029750/5de27e48-4c6e-49e3-99b4-6cf47478d730)

**Comment by sounmind** [comment]
디스코드 채널에서 답변드렸지만,
병현님만의 브랜치를 만든 뒤, 변경사항을 draft Pull Request로 만들어 알려주시면 더 검토하기 좋을 것 같아요
