### ISSUE TITLE
seo meta tag is not applicable for Shadow dom

### ISSUE THREAD

**Issue by SamTheKorean** [DaleStudy/leetcode-website#147]
현재 title과 description을 shadow dom 에서 동적으로 변경해주고 있기 때문에 링크를 공유했을 때 placeholder title이 표시됩니다. <img width="383" alt="Screenshot 2024-07-15 at 12 06 42 AM" src="https://github.com/user-attachments/assets/9c05552c-ed34-42f4-bfbe-2768e4a53ef4">. 

이 문제를 해결하기 위해 shadow dom으로 바로 title을 넣어줄 수 있는 방법을 알아봤더니 title이나 meta 요소는 main dom의 direct child이 되어야하므로 그림 처럼 main dom 하위에 있는 shadow dom 내부에 title 이나 meta element를 직접 주입하는 건 불가능하게 설계되어 있습니다. 
<img width="473" alt="image" src="https://github.com/user-attachments/assets/f0e6cb8c-ce04-4c3f-964a-1bbf454bfa42">
https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM

이와 같은 이유로 seo meta tag는 web component로 만들기 부적절하다라는 결론에 이르렀습니다.

**Comment by SamTheKorean** [comment]
이 티켓으로 seo-meta-tag삭제와 index.html에 기존 요소 추가하는 변경사항을 pr로 만들어도 될까요?

**Comment by sounmind** [comment]
오늘 제보했던 내용을 issue로 잘 만들어주셨군요!
PR로 변경사항 만들어주시면 감사하겠습니다.
그리고 위 내용에 대한 출처나 뒷받침하는 문서를 추가해주면 좋겠어요.
