### ISSUE TITLE
Needs to be fixed : Brief flash of unstyled content (FOUC)

### ISSUE THREAD

**Issue by SamTheKorean** [DaleStudy/leetcode-website#149]

**Comment by SamTheKorean** [comment]
페이지 새로고침 시 프로세스된 html 페이지가 아닌 raw text가 먼저 표시되고 html 페이지로 변경되는 문제가 있습니다. 해당 문제 분석해보고 솔루션 관련 PR올리겠습니다!

**Comment by SamTheKorean** [comment]
https://www.jacobmilhorn.com/posts/solving-fouc-in-web-components/

**Comment by SamTheKorean** [comment]
Web components have to wait for JavaScript to run customElements.define() before encapsulated styles are applied along with the rest of the Shadow DOM. This can cause an ugly Flash of Unstyled Content (FOUC) that is easily remedied by pre-styling the registered component using :not(:defined) CSS pseudo-classes.

**Comment by SamTheKorean** [comment]
다른 레퍼런스도 참고 부탁드립니다! https://web.dev/articles/custom-elements-v1?hl=en#pre-styling_unregistered_elements

**Comment by DaleSeo** [comment]
조치 안 하는 걸로 결정. 혹시 파고 싶은 분은 말리지 않음.
