### ISSUE TITLE
[bug] The plain text is exposed before the JS rendering is complete.

### ISSUE THREAD

**Issue by dev-jonghoonpark** [DaleStudy/leetcode-website#171]
The plain text is exposed until the rendering is complete. (for a few seconds)

<img width="720" alt="image" src="https://github.com/user-attachments/assets/d916edd7-3aee-4812-bde7-794282678ab3">

**Comment by sounmind** [comment]
요 건은 [known issue](https://github.com/DaleStudy/leetcode-website/issues/149)로 현재 대응하지 않기로 했습니다~

**Comment by DaleSeo** [comment]
@dev-jonghoonpark 많이 티가 나던가요? 😅 저희끼리 논의할 때는 크게 티가 나지 않는다고 판단했었거든요 ㅋㅋ

**Comment by dev-jonghoonpark** [comment]
@DaleSeo 앗 일단 눈에 보여서 리포트 드렸네요 ; )
