### ISSUE TITLE
[bug] wrong discord link

### ISSUE THREAD

**Issue by dev-jonghoonpark** [DaleStudy/leetcode-website#173]
The discord link in the body is different from the discord link in the header.
And the Discord link in the body is an invalid invitation.
![image](https://github.com/user-attachments/assets/02e0a812-c02d-4d5c-bda6-af35d0f42a16)
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/1f7cfeef-a985-4956-bb54-04f798e5cf09">

**Comment by yolophg** [comment]
step 컴포넌트에서 사용한 아래 링크로 통일하면 될 것 같습니다.
https://discord.com/invite/6TwzdnW6ze
