### ISSUE TITLE
[proposal] adding box-shadow property to screenshot images

### ISSUE THREAD

**Issue by dev-jonghoonpark** [DaleStudy/leetcode-website#174]
I  suggest adding box-shadow property to screenshot images
I think the images would be better separated.

### before add box-shadow
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/0a4bb15d-4e58-47fe-b7cb-5377634081a0">

### after add box-shadow
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/19b46959-77bf-401a-ade3-42fcd66f7a3f">

```css
box-shadow: 0 10px 16px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19) !important;
```

**Comment by DaleSeo** [comment]
@nhistory 님, 위 디자인 제안 리뷰 좀 부탁드릴께용!

**Comment by nhistory** [comment]
@DaleSeo 피그마 프로젝트에 이미지마다 drop shadow 설정을 넣어놨는데 웹사이트에 반영이 안되어 있었네요 ;;

![image](https://github.com/user-attachments/assets/6529ca7c-3c1d-48fb-abd1-947110855aba)

```css
box-shadow: 2px 2px 4px 0 var(--bg-300);
```

위와 같이 적용되면 좋을 것 같습니다.
