### ISSUE TITLE
Create Header Component

### ISSUE THREAD

**Issue by SamTheKorean** [DaleStudy/leetcode-website#23]
Including logo, brand name

**Comment by SamTheKorean** [comment]
헤더를 달레님 웹사이트 처럼 스크롤 해도 고정되고 다른 요소 상위에 두고 opacity를 조절하는게 좋을까요?`https://www.daleseo.com/`

**Comment by nhistory** [comment]
저는 1번에 한표 던집니다 ㅎㅎ

**Comment by SamTheKorean** [comment]
그럼 1번처럼 개발해보겠습니다~!

**Comment by SamTheKorean** [comment]
link-component를 임포트해서 재활용해서 header 컴포넌트를 완성하는게 좋을 것 같아서 나머지 부분은 현재 link-component pr merge 된 후 pull 받아서 구현하겠습니다!
https://github.com/DaleStudy/leetcode-website/assets/104721736/6be73ee4-7ec9-46c5-b00d-a86b7c45cc48
