### ISSUE TITLE
Create SEO Component

### ISSUE THREAD

**Issue by SamTheKorean** [DaleStudy/leetcode-website#25]

**Comment by DaleSeo** [comment]
@SamTheKorean 이 티켓 왜 닫게 되었는지 혹시 기억하시낭요? SEO 컴포넌트가 없길래 여쭙니당.

**Comment by SamTheKorean** [comment]
네 seo요소를 동적으로 로드하게 되면 처음 url을 복붙하면 placeholder 타이틀이 보여서 index.html로 옮겼습니다!

**Comment by SamTheKorean** [comment]
seo 부분도 client side rendering의 단점같네요.
