### ISSUE TITLE
fix website title not working bug

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#29]
- website title이 정상 작동하지 않음.

**Comment by SamTheKorean** [comment]
@sounmind  혹시 어디 부분에서 버그가 있는 걸까요? 
<img width="1411" alt="Screenshot 2024-06-11 at 12 46 24 PM" src="https://github.com/DaleStudy/leetcode-website/assets/104721736/6d7a5517-5e8d-4e18-a885-6819b6774423">

**Comment by SamTheKorean** [comment]
제가 전에 main에서 만든 header 관련 브렌치 만든 거에서는 정상 작동하는데 main으로 checkout하니 브렌치에서 다시 실행해보니 버그가 재현되네요 확인해보겠습니다!

**Comment by sounmind** [comment]
> 제가 전에 main에서 만든 header 관련 브렌치 만든 거에서는 정상 작동하는데 main으로 checkout하니 브렌치에서 다시 실행해보니 버그가 재현되네요 확인해보겠습니다!

작성하신 컴포넌트가 적용된 페이지에서 title이 의도한 대로 작동하지 않더라고요.
나중에 제가 할당해드리려고 했는데 알림이 갔나보군요😂
확인 감사합니다. 천천히 보셔요~

**Comment by SamTheKorean** [comment]
확인해보니 footer-link.js 파일에 에러가 있어 main.js 임포트 하는 과정에서 에러가 생겨서 나머지 main.js에 있는 나머지 파일들도 로드가 안돼서 발생한 에러입니다. main.js에서 footer-link.js import 부분 주석처리 후 browser cashes 삭제하고 테스트하니 정상작동합니다!
<img width="1417" alt="Screenshot 2024-06-11 at 1 05 19 PM" src="https://github.com/DaleStudy/leetcode-website/assets/104721736/a4babb1d-b5ee-4393-addc-fdd3e7388e4c">

**Comment by sounmind** [comment]
아항 #31 에서 전파됐군요. 확인해주셔서 감사합니다 ☺️

**Comment by sounmind** [comment]
#31 을 해결하는 PR에서 이 이슈도 닫도록 하면 어떨까 싶네요..!

**Comment by SamTheKorean** [comment]
넵넵! 좋을 것 같습니다!

**Comment by SamTheKorean** [comment]
현재 구조에서는 한 js파일에 문제가 있으면 전체가 작동을 안하게 되는데 원할한 디버깅을 위해 컴포넌트별 독립성을 유지할 수 있는 방안이 뭐가 있을 지 한 번 알아보겠습니다!
