### ISSUE TITLE
Footer Link Component Bug

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#31]
@bhyun-kim 님 버그를 고쳐봅시다!
이 버그 때문에 다른 컴포넌트 코드가 실행되지 않고 있습니다.

![Image](https://github.com/DaleStudy/leetcode-website/assets/37020415/6a3dfc44-27e2-4802-9d8a-2cd380febc8e)
![Image](https://github.com/DaleStudy/leetcode-website/assets/37020415/25d9fa6b-484d-4442-af5a-30a517e285d9)

왜 발생했고, 어떻게 하면 이런 버그를 방지할 수 있을까요?
그리고 이런 버그를 발견했을 때 어떤 과정으로 고치는지도 집중해보면 좋겠습니다.

**Comment by yolophg** [comment]
추가로 버그 픽스에 힌트를 드리자면, 제가 suggestion 했던 코드를 그대로 복사하신 것 같은데, 기존에 이미 있는 constructor() 내로 옮기라는 의미였기에 다시 생성하실 필요는 없으십니다.
그리고, updateLink() 메소드는 제가 첨에 updateLinkHref()로 네이밍했다가 수정했어서 typo를 냈었네요. 그래서, 혼선을 드린 것 같습니다. 
당연하게도, 하나의 메소드의 네이밍은 통일 되어야하므로 통일해주시면 되겠습니다!
