### ISSUE TITLE
If a new change is pushed to a PR that was approved, shouldn't it be unapproved?

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#34]
Currently, changes made after the PR's approval are retained in the approval state.

It seems to me that changes made after approval should be reviewed and shouldn't remain approved because they weren't approved. 

Why not add that rule to the repository PR rules?

**Comment by DaleSeo** [comment]
PR 작성자가 다시 리뷰가 필요한 경우 스스로 dismiss 하기
