### ISSUE TITLE
Meeting 3

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#35]
## Agenda

- How was your week? (Sprint Retro)
  - 각자 하고 싶은 말 공유

- Task Management ([Discord Message Link](https://discord.com/channels/775115965964222492/1245566478288158750/1249562202227216385))
  - **backlog에서 issue 만들기. issue와 PR을 연결시키기.**
  - **중복, 복잡성 방지하기 위해 PR을 project와 연결시키기 말기.**
- #34 
- Design for Mobile, Tablet(style decision for responsive design)
- Code Verification in JS(*Make sure to check the console) by @yolophg 
  - 병합 전 콘솔을 한 번 더 확인하자!
  - 보통의 프로젝트의 경우, 소프트웨어 품질을 검증하기 위한 여러 도구를 도입함.
    - 예: Typescript, Linting Tool, **Testing**

## Action Item

- [x] PR Template 만들어 정상 작동을 확인했냐는 체크박스 만들기
- [x] Favicon 추가
- [x] CSS까지 js 파일에 합쳐서 폴더 없이 하나의 파일로 웹 컴포넌트 작성하기

## Retro of meeting

- KEEP
- PROBLEM
- TRY

**Comment by SamTheKorean** [comment]
저렇게 묶으니 간결하군요! 감사합니다ㅎㅎ
