### ISSUE TITLE
create CONTRIBUTING.md

### ISSUE THREAD

**Issue by sounmind** [DaleStudy/leetcode-website#60]

**Comment by DaleSeo** [comment]
@sounmind [요거](https://github.com/DaleStudy/leetcode-website/pull/72#discussion_r1650173525)는 반영 좀 해주시지 ㅠㅠ

**Comment by sounmind** [comment]
@DaleSeo 오? 모바일로 보니 세부 코멘트가 안 보였네요! 다시 반영해서 PR 올릴게요~!!

**Comment by sounmind** [comment]
@DaleSeo https://github.com/DaleStudy/leetcode-website/pull/73 여기에 반영해두었습니다 🙇‍♂️
