### ISSUE TITLE
Component Dashboard

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leetcode-website#65]
틀린 정보가 있을 수 있습니다. 만일 그렇다면 업데이트 부탁드립니다 🙇‍♂️

| Component Name   | Low Fidelity | Responsive Design | High Fidelity |
|------------------|--------------|-------------------|---------------|
| button-link      | Done         | Done              | Done          |
| footer           | Done         |                   |               |
| footer-link      | Done         |                   |               |
| header           | Done         |                   |               |
| hero             | Done         |                   |               |
| icon-link        |              |                   |               |
| image            |              |                   |               |
| review-item      | Done         | Done               |  Done             |
| seo-meta-tag     | Done         | No Need           | No Need       |
| step             |              |                   |               |
| intro-section             |              |                   |               |

---

## 고민해야 할 것들
- 현재 컴포넌트 구성만으로 모든 요구사항을 구현할 수 없음. 새로운 컴포넌트들이 필요함.

![Image](https://github.com/DaleStudy/leetcode-website/assets/37020415/d2437b88-20bf-4367-9eb5-c24318685afc)

## 새로 필요한 컴포넌트들
- [x] review-list
- [x] step-list

- (section)
  - [x] Intro section
  - [x] contributors-languages section
  - [x] code-review section
  - [x] participant-testimonials section
  - [x] study-participation-steps section

**Comment by sounmind** [comment]
## 고민해야 할 것들
- 현재 컴포넌트 구성만으로 모든 요구사항을 구현할 수 없음. 새로운 컴포넌트들이 필요함.

## 새로 필요한 컴포넌트들
- review-list
- step-list

- (section)
  - Intro
  - contributors-languages
  - code-review
  - participant-testimonials
  - study-participation-steps

**Comment by DaleSeo** [comment]
page 컴포넌트는 일단 필요없는 걸로...

**Comment by DaleSeo** [comment]
@sounmind 프로젝트 디테일로 내용을 옮겨주시고 이슈는 닫아주세용

**Comment by sounmind** [comment]
옮기기 완료
