### ISSUE TITLE
Fix Extension Validation Error in Footer Icon

### ISSUE THREAD

**Issue by bhyun-kim** [DaleStudy/leetcode-website#86]
![Uploading image.png…]()

**Comment by DaleSeo** [comment]
@bhyun-kim 님 앞으로 이슈 생성하실 때는 프로젝트를 지정해주실 수 있으실가요? 그러면 백로그 관리에 큰 도움이 될 것 같아요!

![Shot 2024-06-27 at 08 09 45@2x](https://github.com/DaleStudy/leetcode-website/assets/5466341/d619aa50-64df-4066-ba96-5ccde3a41879)

**Comment by sounmind** [comment]
## 에러 발생 위치
![image](https://github.com/DaleStudy/leetcode-website/assets/37020415/f176fa33-2d6a-4ad6-a3df-ded824e0864e)
![image](https://github.com/DaleStudy/leetcode-website/assets/37020415/6b609be1-e85a-4d20-b082-b6ad8d598ca1)

**Comment by bhyun-kim** [comment]
> @bhyun-kim 님 앞으로 이슈 생성하실 때는 프로젝트를 지정해주실 수 있으실가요? 그러면 백로그 관리에 큰 도움이 될 것 같아요!
> 
> ![Shot 2024-06-27 at 08 09 45@2x](https://private-user-images.githubusercontent.com/5466341/343764371-d619aa50-64df-4066-ba96-5ccde3a41879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTgwMTAsIm5iZiI6MTcxOTQ5NzcxMCwicGF0aCI6Ii81NDY2MzQxLzM0Mzc2NDM3MS1kNjE5YWE1MC02NGRmLTQwNjYtYmE5Ni01Y2NkZTNhNDE4NzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMTQxNTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTZiOTY4MmJkZDIyZTY2NmU0NDg2OGIzODM0NDlkMGRkODM3NzA3MTZhNzE4NzMwMDI4YWRjNWM5MzM5ODE5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wFDCdzlqDUKhRJD02AQ7wu6NTZvYs9i_o8yFoUVXtoM)

넵 알겠습니다! 확인해주셔서 감사드려요 ㅎㅎ
