### ISSUE TITLE
어떻게 속성을 넘기지 않을 수 있을까?

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leetcode-website#91]
웹 컴포넌트를 사용할 때 선택 속성을 명시하지 않은 경우 해당 속성을 `this.getAttribute()`로 읽어오면 `null`이 나온다. 웹 컴포넌트의 구현에서 사용하는 HTML 요소에도 굳이 이 속성을 넘기지 않아도 되는 경우에는 어떻게 처리 하는 것이 좋을까?

https://github.com/DaleStudy/leetcode-website/blob/193d140a6d7a2f43c1fe02186930ae7ad6bac7bb/index.html#L268-L276

## Concetanating HTML tokens

- 현재 구현 방식
- 완전히 Declartive하지도 않고, 그렇다고 Iterative하지도 않은 애매한 느낌
- 가독성이 떨어지고, 버그 위험이 높고, 유지보수가 힘듬

https://github.com/DaleStudy/leetcode-website/blob/193d140a6d7a2f43c1fe02186930ae7ad6bac7bb/components/image.js#L31-L50

## Seting default attribute values manually

- 속성이 넘어오지 않은 경우, 개발자가 일일이 기본값으로 직접 지정
- MDN을 참조해서 속성의 기본값을 파악해야 하는데, 가끔 MDN에도 기본값이 무엇인지 정확히 언급되어 있지 않은 경우가 있음
- 최종 HTML 코드가 기본값 설정 때문에 불필요하게 verbose, redundant 해질 수 있음
- 그래도 구현은 상당히 깔끔해짐

```js
  createHtml() {
    const src = this.getAttribute("src") || "";
    const alt = this.getAttribute("alt") || "";
    const width = this.getAttribute("width") || "auto";
    const height = this.getAttribute("height") || "auto";

    return `<img src="${src}" alt="${alt}" width="${width}" height="${height}" />`;
  }
```

## Filtering out null attributes

- 속성이 넘어오지 않은 경우, 자동으로 HTML 요소에 해당 속성이 생략되도록 약간의 구현
- 보일러 플레이트 코드를 유틸리티화 할 수도 있음
- 모든 경우에 다 통할지 아직 확신이 안 섬

```js
  createHtml() {
    const attributeNames = ["src", "alt", "width", "height"];
    const attributesString = attributeNames
      .filter((name) => this.hasAttribute(name))
      .map((name) => `${name}="${this.getAttribute(name)}"`)
      .join(" ");

    return `<img ${attributesString} />`;
  }
```

**Comment by sounmind** [comment]
아래처럼 빈 문자열을 할당하는 방식으로 작성할 수도 있겠습니다.

```js
return `<img 
  ${src ? `src="${src}"` : ''}
  ${alt ? `alt="${alt}"` : ''}
  ${width ? `width="${width}"` : ''}
  ${height ? `height="${height}"` : ''}
/>`;
```

매번 삼항연산자를 작성하는 것이 번거롭고 가독성에 안 좋다면 유틸함수를 만들어 간소화 시킬 수도 있습니다.

```js
function attr(attributes) {
  return Object.entries(attributes)
    .filter(([_, value]) => value != null)
    .map(([key, value]) => `${key}="${value}"`)
    .join(' ');
}
```

```js
return `
  <img 
    ${attr({ src })} 
    ${attr({ alt })} 
    ${attr({ width })} 
    ${attr({ height })} 
  />
`;
```
```js
return `<img ${attr({ src, alt, width, height })} />`;
```

**Comment by DaleSeo** [comment]
> ```js
> return `<img 
>   ${src ? `src="${src}"` : ''}
>   ${alt ? `alt="${alt}"` : ''}
>   ${width ? `width="${width}"` : ''}
>   ${height ? `height="${height}"` : ''}
> />`;
> ```

@sounmind 님 솔루션이 더 나은 것 같습니다! 👏 역시... 우리의 🧠

**Comment by SamTheKorean** [comment]
유틸함수를 만들어 사용하는 편이 boilerplate를 줄일 수 있어서 좋아보입니다!

**Comment by DaleSeo** [comment]
삼항 연산자를 사용하는 방식으로 결정
