### ISSUE TITLE
Hard to see which element has focus

### ISSUE THREAD

**Issue by DaleSeo** [DaleStudy/leetcode-website#96]
현재 웹페이지에서 버튼이나 링크를 마우스로 클릭하거나 키보드 탭으로 이동할 때 어떤 요소에 현재 포커스가 있는지 ~유관~육안으로 전혀 파악이 불가능합니다. 웹 접근성 측면에서 큰 이슈이오니 반드시 조치가 되야할 것 같습니다. 관련 컴포넌트에 `:focus`나 `:focus-visible` 가상 클래스에 대한 스타일이 추가되야 할 듯 합니다. 혹시 도움이 될까하여 관련 블로그 포스팅을 공유드릴께요: https://www.daleseo.com/css-focus/

**Comment by sounmind** [comment]
유관이 혹시 어떤 뜻인지 정확하게 알 수 있을까요? 혹시 시각적으로("육안")으로 파악하기 어렵다는 말씀이실까요?!!

**Comment by sounmind** [comment]
전적으로 동의하나 구현 우선순위를 정기 미팅에서 이야기해보면 좋을 것 같아요. 예를 들어, 이제부터 컴포넌트 구현 시 항상 focusable로 구현할 것인지? 아니면 일단 구현부터 한 다음 일괄적으로 적용할 것인지를요!

**Comment by DaleSeo** [comment]
> 전적으로 동의하나 구현 우선순위를 정기 미팅에서 이야기해보면 좋을 것 같아요. 예를 들어, 이제부터 컴포넌트 구현 시 항상 focusable로 구현할 것인지? 아니면 일단 구현부터 한 다음 일괄적으로 적용할 것인지를요!

@sounmind 넵, 잃어버러지 않으려고 우선 백로그에 이슈만 추가해놓은 것입니다. 오늘 모임 때 함께 얘기하시죠 :)

**Comment by DaleSeo** [comment]
티켓 4개 생성
